# permissions for end users to view loadtests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: loadtest-viewer-role
rules:
- apiGroups:
  - e2etest.grpc.io.e2etest.grpc.io
  resources:
  - loadtests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - e2etest.grpc.io.e2etest.grpc.io
  resources:
  - loadtests/status
  verbs:
  - get
