# See ../pkg/defaults/defaults.go for documentation on each field.

componentNamespace: default

driverPool: drivers

workerPool: workers-16core

driverPort: 10000

serverPort: 10010

cloneImage: docker.pkg.github.com/grpc/test-infra/clone

driverImage: docker.pkg.github.com/grpc/test-infra/driver

languages:
  - language: cxx
    buildImage: l.gcr.io/google/bazel:latest
    runImage: docker.pkg.github.com/grpc/test-infra/cxx

  - language: java
    buildImage: gradle:jdk8
    runImage: docker.pkg.github.com/grpc/test-infra/java

  - language: go
    buildImage: golang:1.14
    runImage: docker.pkg.github.com/grpc/test-infra/go

  - language: python
    buildImage: l.gcr.io/google/bazel:latest
    runImage: gcr.io/grpc-testing/e2etest/runtime/python3.7
